### ISSUE TITLE
It is necessary to correct the documentation for Angular 5

### ISSUE THREAD

**Issue by splincode** [mgechev/angular-performance-checklist#14]
For example, now you need to use not trackBy, but trackByFunction.

**Comment by mgechev** [comment]
Hey @splincode it looks like the interface of the function is `TrackByFunction<T>` but it's still set using `trackBy` in the `*ngFor`. Let me know if I am misunderstanding your question.

**Comment by tiaguinho** [comment]
Changelog of Angular says:
**core**: TrackByFn has been removed because it was deprecated since v4. Use TrackByFunction instead.

**Comment by mgechev** [comment]
I see, this means that the interface for the `TrackByFunction` has changed. This doesn't impact this document.
