### ISSUE TITLE
Use pipes instead of function calls in templates

### ISSUE THREAD

**Issue by mohammedzamakhan** [mgechev/angular-performance-checklist#24]

**Comment by mgechev** [comment]
There's a section about pure pipes.

If you have a moment, you can add a new one on using pipes instead of side-effect free methods.

**Comment by ZQ-jhon** [comment]
need translate this checklist to chinese ?

**Comment by mgechev** [comment]
Sure! Translation is very welcome!

**Comment by ZQ-jhon** [comment]
> Sure! Translation is very welcome!

hey, i was translated it and created a PR :  [#34](https://github.com/mgechev/angular-performance-checklist/pull/34)

**Comment by mgechev** [comment]
Closing this issue for now.
