### ISSUE TITLE
Question: ComponentMetadata Default Value

### ISSUE THREAD

**Issue by williamxsp** [mgechev/angular-performance-checklist#38]
> Thankfully, we don't have to do this manually. The ComponentMetadata interface provides the property preserveWhitespaces which by default has value false, because removing the whitespace always may influence the DOM layout. In case we set the property to false Angular will trim the unnecessary whitespace which will lead to further reduction of the bundle size.

Should we set it to true right?

**Comment by mgechev** [comment]
Yes, that's a mistake. Thanks for the catch! Also, currently `preserveWhitespaces` is always `false`.

**Comment by Achilles1515** [comment]
@mgechev Isn't this now description of `preserveWhitespace `now incorrect?

It currently reads:

> In case we set the property to true Angular will trim the unnecessary whitespace...

But the [Angular docs](https://angular.io/api/core/Component#preserveWhitespaces) read:

> As of Angular 6, the default for preserveWhitespaces is false (whitespace is removed)

So this performance checklist is saying `true `will trim whitespace but the docs state `false `removes whitespace.

Also, I feel like the grammar of the quoted sentence above ("In case we set") is weird and can be made more clear by just saying:

> Setting `preserveWhitespace` to `false` will trim unnecessary whitespace, further reducing the bundle size.

**Comment by mgechev** [comment]
@Achilles1515 you're absolutely right, sorry for the confusion. Let me know if the change in [this commit](https://github.com/mgechev/angular-performance-checklist/commit/94f71a523cc77316ee676142cb1dc7502bffbdd7) makes it clear.

**Comment by Achilles1515** [comment]
> @Achilles1515 you're absolutely right, sorry for the confusion. Let me know if the change in [this commit](https://github.com/mgechev/angular-performance-checklist/commit/94f71a523cc77316ee676142cb1dc7502bffbdd7) makes it clear.

Looks correct now. I appreciate the quick fix.
