### ISSUE TITLE
Can I get some clarification on ngZoneEventCoalescing feature flag?

### ISSUE THREAD

**Issue by yzhe554** [mgechev/angular-performance-checklist#52]
Hi @mgechev , I found this feature by reading https://twitter.com/yurzui/status/1327248065137430528?s=20. And then I checked the source code https://github.com/angular/angular/blob/master/packages/core/src/application_ref.ts#L268.
Everything I can find seems saying this is a performance enhancement.
Is there any side effects that stops Angular turn it on by default?
If this is definitely a performance enhancement feature, should we add to this doco?
Thanks in advance.

**Comment by mgechev** [comment]
It's definitely worth it mentioning it here in the performance checklist! Would you want to open a pull request?

Enabling it by default could break existing apps. Currently, we run change detection every time when the microtask queue is empty, which is far more often compared to scheduling it with `requestAnimationFrame`. Existing apps that rely on this behavior would not have their UI up to date.

If you open a pull request, would you mention this as a disclaimer?

**Comment by yzhe554** [comment]
Thanks for clarification. And sure, I will draft a PR soon.
