### ISSUE TITLE
Wrong property name?

### ISSUE THREAD

**Issue by jlorenzoC** [mgechev/angular-performance-checklist#55]
I think in the code example here: [run-outside-angular](https://github.com/mgechev/angular-performance-checklist#run-outside-angular) , there is a call to a property that doesn't exist? 

![Inkedfirefox_6sioj6cPkU_LI](https://user-images.githubusercontent.com/43883758/133914974-29254bd2-449a-4682-8df5-83a16d1adbca.jpg)

**Comment by mgechev** [comment]
Would you open a PR to update?
